[package]
name = "despawn-docs"
version = "0.1.0"
edition = "2021"

[features]
default = []
debug = []

[dependencies]
anyhow = "1.0.86"
clap = { version = "4.5.7", features = ["derive"] }
lazy_static = "1.5.0"
thiserror = "1.0.61"
